# Copyright (c) 2019 Oracle and/or its affiliates,  All rights reserved.

name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TF_VAR_fingerprint: ${{ secrets.TF_VAR_fingerprint }}
      TF_VAR_private_key: ${{ secrets.TF_VAR_private_key }}
      TF_VAR_ssh_private_key: ${{ secrets.TF_VAR_ssh_private_key }}
      TF_VAR_tenancy_id: ${{ secrets.TF_VAR_tenancy_id }}
      TF_VAR_user_id: ${{ secrets.TF_VAR_user_id }}
      TF_VAR_ssh_authorized_keys: ${{ secrets.TF_VAR_ssh_authorized_keys }}
    steps:
    - uses: actions/checkout@v1
    - uses: cosmindev/terraform-oci-compute-instance/.github/actions/terraform-test@master